project:
  id: 2026-02-02-exp001
  root_dir: "./output"
  description: "测试代码"

capture_settings:
  exposure_us: 104546.0000
  monitor_idx: 1
  scale_factor: 0.2
  display_position:    # 功能需要在代码里面修改以启用
  display_image_path: "D:/qjy/260202/SLMImagingPipeline/data/example/分辨率测试卡.jpg"
  slm_image_path: "D:/qjy/260202/SLMImagingPipeline/data/example/分辨率测试卡.jpg"

physical_setup:
  object_name: "扑克牌"
  brightness: 4060
  sensor_mask_distance: "未测量"
  mask_object_distance: "6*2.5cm"
  point_light_brightness: 4010
  mask_LED-light_distance: "6*2.5cm"
  